### ISSUE TITLE
[fix]: Fix Font on createAccount form

### ISSUE THREAD

**Issue by vaishali86c** [vaishali86c/SkillMate#5]
This text inconsistent or incorrect.

![18 09 2023_15 49 16_REC](https://github.com/vaishali86c/SkillMate/assets/109902140/33172010-aae9-45f1-b6bc-278ca5251269)

**Comment by sushant4612** [comment]
i am not getting whats the issue can you explain me in detail what you want

**Comment by vaishali86c** [comment]
you are looking to find highlighted text in a project where the text is in a different font, correct?
you want to  change that font .

**Comment by prasadkhotkar** [comment]
It's very simple just go to form tag and add one class of any name and give font-family as you want .
This issue raise due to you added font family to labels in above containers so font family of all labels in create account also changing and h1 tag others font family not changing.
